overrides:
  blockly: 'file:vendor/aily-project-blockly-13.3.0-aily.5d59fc955336.tgz'
  '@blockly/field-colour': 13.3.0
  '@blockly/field-grid-dropdown': 13.3.0

allowBuilds:
  '@parcel/watcher': true
  electron: true
  esbuild: true
  lmdb: true
  msgpackr-extract: true
