// Source-only regression: first complete layout rewrite from the reported 10:53 session.
// No project paths, private baseline, persisted IDs or credentials.
export const layoutSource = "# ABS Schema: 2\n# Project Data Schema: 1 (external-only)\n\narduino_global()\n    variable_define(\"temperature\", float, math_number(0))\n    variable_define(\"humidity\", float, math_number(0))\n    variable_define(\"lastUpdate\", uint32_t, math_number(0))\narduino_setup()\n    serial_begin(Serial, \"115200\")\n    dht_init(\"dht\", DHT11, D3)\n    u8g2_begin(SSD1306, FULL_BUFFER, \"128X64_NONAME\", _HW_I2C, \"D5\", \"D4\", \"U8X8_PIN_NONE\")\narduino_loop()\n    controls_if(logic_compare(math_arithmetic(time_millis(), MINUS, variables_get($lastUpdate)), GTE, math_number(2000)))\n        variables_set($lastUpdate, time_millis())\n        variables_set($temperature, dht_read_temperature($dht))\n        variables_set($humidity, dht_read_humidity($dht))\n        serial_println(Serial, text_join(text(\"Temp: \"), number_to_string(variables_get($temperature)), text(\" C  Humi: \"), number_to_string(variables_get($humidity)), text(\" %\")) @extra:{\"itemCount\":5})\n        serial_println(Serial, logic_ternary(logic_operation(logic_operation(logic_compare(variables_get($temperature), GTE, math_number(18)), AND, logic_compare(variables_get($temperature), LTE, math_number(28))), AND, logic_operation(logic_compare(variables_get($humidity), GTE, math_number(30)), AND, logic_compare(variables_get($humidity), LTE, math_number(70)))), text(\"环境舒适\"), text(\"环境不舒适\")))\n        u8g2_clear_buffer()\n        u8g2_set_font(\"19\", CHINESE, u8g2_font_wqy16_t_chinese1)\n        u8g2_draw_str(math_number(0), math_number(22), text_join(text(\"Temp: \"), number_to_string(variables_get($temperature)), text(\" C\")) @extra:{\"itemCount\":3})\n        u8g2_draw_str(math_number(0), math_number(54), text_join(text(\"Humi: \"), number_to_string(variables_get($humidity)), text(\" %\")) @extra:{\"itemCount\":3})\n        u8g2_draw_str(math_number(0), math_number(38), logic_ternary(logic_operation(logic_operation(logic_compare(variables_get($temperature), GTE, math_number(18)), AND, logic_compare(variables_get($temperature), LTE, math_number(28))), AND, logic_operation(logic_compare(variables_get($humidity), GTE, math_number(30)), AND, logic_compare(variables_get($humidity), LTE, math_number(70)))), text(\"舒适\"), text(\"不舒适\")))\n        u8g2_send_buffer()";
export const layoutEdits = [
  {
    "oldText": "    variable_define(\"lastUpdate\", uint32_t, math_number(0))\narduino_setup()",
    "newText": "    variable_define(\"lastUpdate\", uint32_t, math_number(0))\n    variable_define(\"tempInt\", int, math_number(0))\n    variable_define(\"humiInt\", int, math_number(0))\narduino_setup()"
  },
  {
    "oldText": "        variables_set($temperature, dht_read_temperature($dht))\n        variables_set($humidity, dht_read_humidity($dht))\n        serial_println(Serial, text_join(text(\"Temp: \"), number_to_string(variables_get($temperature)), text(\" C  Humi: \"), number_to_string(variables_get($humidity)), text(\" %\")) @extra:{\"itemCount\":5})",
    "newText": "        controls_if(dht_read_success($dht))\n            variables_set($temperature, dht_read_temperature($dht))\n            variables_set($humidity, dht_read_humidity($dht))\n            variables_set($tempInt, math_round(ROUND, variables_get($temperature)))\n            variables_set($humiInt, math_round(ROUND, variables_get($humidity)))\n            serial_println(Serial, text_join(text(\"Temp: \"), number_to_string(variables_get($tempInt)), text(\" C  Humi: \"), number_to_string(variables_get($humiInt)), text(\" %\")) @extra:{\"itemCount\":5})"
  },
  {
    "oldText": "        serial_println(Serial, logic_ternary(logic_operation(logic_operation(logic_compare(variables_get($temperature), GTE, math_number(18)), AND, logic_compare(variables_get($temperature), LTE, math_number(28))), AND, logic_operation(logic_compare(variables_get($humidity), GTE, math_number(30)), AND, logic_compare(variables_get($humidity), LTE, math_number(70)))), text(\"环境舒适\"), text(\"环境不舒适\")))\n        u8g2_clear_buffer()\n        u8g2_set_font(\"19\", CHINESE, u8g2_font_wqy16_t_chinese1)\n        u8g2_draw_str(math_number(0), math_number(22), text_join(text(\"Temp: \"), number_to_string(variables_get($temperature)), text(\" C\")) @extra:{\"itemCount\":3})\n        u8g2_draw_str(math_number(0), math_number(54), text_join(text(\"Humi: \"), number_to_string(variables_get($humidity)), text(\" %\")) @extra:{\"itemCount\":3})\n        u8g2_draw_str(math_number(0), math_number(38), logic_ternary(logic_operation(logic_operation(logic_compare(variables_get($temperature), GTE, math_number(18)), AND, logic_compare(variables_get($temperature), LTE, math_number(28))), AND, logic_operation(logic_compare(variables_get($humidity), GTE, math_number(30)), AND, logic_compare(variables_get($humidity), LTE, math_number(70)))), text(\"舒适\"), text(\"不舒适\")))\n        u8g2_send_buffer()",
    "newText": "        serial_println(Serial, logic_ternary(dht_read_success($dht), logic_ternary(logic_operation(logic_operation(logic_compare(variables_get($temperature), GTE, math_number(18)), AND, logic_compare(variables_get($temperature), LTE, math_number(28))), AND, logic_operation(logic_compare(variables_get($humidity), GTE, math_number(30)), AND, logic_compare(variables_get($humidity), LTE, math_number(70)))), text(\"环境舒适\"), text(\"环境不舒适\")), text(\"传感器读取失败\")))\n        u8g2_clear_buffer()\n        u8g2_set_draw_color(\"1\")\n        u8g2_draw_rectangle(math_number(0), math_number(0), math_number(128), math_number(18), TRUE)\n        u8g2_set_draw_color(\"0\")\n        u8g2_set_font(\"19\", CHINESE, u8g2_font_wqy16_t_chinese1)\n        u8g2_draw_str(math_number(4), math_number(14), text(\"环境监测\"))\n        u8g2_set_font(\"8\", CHINESE, u8g2_font_wqy12_t_chinese1)\n        u8g2_draw_str(math_number(78), math_number(13), logic_ternary(dht_read_success($dht), logic_ternary(logic_operation(logic_operation(logic_compare(variables_get($temperature), GTE, math_number(18)), AND, logic_compare(variables_get($temperature), LTE, math_number(28))), AND, logic_operation(logic_compare(variables_get($humidity), GTE, math_number(30)), AND, logic_compare(variables_get($humidity), LTE, math_number(70)))), text(\"舒适\"), text(\"不舒适\")), text(\"错误\")))\n        u8g2_set_draw_color(\"1\")\n        u8g2_draw_line(math_number(62), math_number(23), math_number(62), math_number(61))\n        u8g2_draw_str(math_number(8), math_number(36), text(\"温度\"))\n        u8g2_draw_str(math_number(68), math_number(36), text(\"湿度\"))\n        u8g2_set_font(\"19\", HELV_B, u8g2_font_helvB18_tr)\n        u8g2_draw_str(math_number(8), math_number(61), text_join(number_to_string(variables_get($tempInt)), text(\" C\")))\n        u8g2_draw_str(math_number(68), math_number(61), text_join(number_to_string(variables_get($humiInt)), text(\" %\")))\n        u8g2_send_buffer()"
  }
];
